### ISSUE TITLE
Species are showing up without common name and without conservation status & most of species are not evaluated

### ISSUE THREAD

**Issue by koonchaya** [rfcx/engineering-support#255]
Original post: https://rfcx.slack.com/archives/C03FD1WD02J/p1673383140493649

**Issue description:**
Hey guys, species are showing up without common name and without conservation status according to IUCN on the Arbimon Insights page. I've tested previewing several different projects and it looks like the issue is occurring in all projects.

**Steps to reproduce:**
1. Enter any project on the Arbimon Insights page (e.g., https://bio.rfcx.org/weforest-wildlife-corridors/spotlight/ammodramus-humeralis)
2. Check conservation status on dashboard tab and common name and conservation status on spotlight tab.
3. 
**Expected result:**
The number of species in each threat category according to the IUCN and the popular name appear in the spotlight tab.

**Actual result:**
It is not showing the popular name and conservation status for any species, all are listed as not evaluated.

**Additional details:**
This is happening in all projects on the Arbimon Insights page.

![Image](https://user-images.githubusercontent.com/87486094/211799068-d390c361-21bc-409c-bce6-2b49d353dc4c.png)

From the screenshot most of the species are not evaluated (97% not evaluated).

**Comment by koonchaya** [comment]
Rename species names on the Arbimon side + remove 1 species with moving all detections to a new one

**Comment by rassokhina-e** [comment]
Fixed!

**Comment by koonchaya** [comment]
Need to discuss more in the future
> Hi 
[@Noon](https://rfcx.slack.com/team/U01K4E2092N)
. The situation is better, but it is still not ideal, because browsing through some projects I still see a variable number of species as "not evaluated" and I believe it is due to these problems with name changes (some species included in these projects in Arbimon with names that are not being used by the IUCN). We need to see a way to make it possible to include in Arbimon only the most current nomenclature used by the IUCN (I don't know if this would be ideal and possible). Perhaps we should discuss this further when Marconi returns. Or in the future, before including a species in any project in Arbimon, we would first check the name adopted by the IUCN, to avoid having this type of problem. Although the ideal would be for this to be automated.
